#!/usr/bin/env bash
# Display "Best School" 10 times, with special output on the 9th iteration
i=1
while [ $i -le 10 ]
do
  echo "Best School"
  if [ $i -eq 9 ]
  then
    echo "Hi"
  fi
  ((i++))
done
